// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewUrlService creates a new instance of UrlService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlService {
	mock := &UrlService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UrlService is an autogenerated mock type for the UrlService type
type UrlService struct {
	mock.Mock
}

type UrlService_Expecter struct {
	mock *mock.Mock
}

func (_m *UrlService) EXPECT() *UrlService_Expecter {
	return &UrlService_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type UrlService
func (_mock *UrlService) Create(ctx context.Context, originalURL string) (string, error) {
	ret := _mock.Called(ctx, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, originalURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, originalURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UrlService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UrlService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - originalURL string
func (_e *UrlService_Expecter) Create(ctx interface{}, originalURL interface{}) *UrlService_Create_Call {
	return &UrlService_Create_Call{Call: _e.mock.On("Create", ctx, originalURL)}
}

func (_c *UrlService_Create_Call) Run(run func(ctx context.Context, originalURL string)) *UrlService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UrlService_Create_Call) Return(s string, err error) *UrlService_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UrlService_Create_Call) RunAndReturn(run func(ctx context.Context, originalURL string) (string, error)) *UrlService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type UrlService
func (_mock *UrlService) Get(ctx context.Context, id string) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UrlService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UrlService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *UrlService_Expecter) Get(ctx interface{}, id interface{}) *UrlService_Get_Call {
	return &UrlService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UrlService_Get_Call) Run(run func(ctx context.Context, id string)) *UrlService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *UrlService_Get_Call) Return(s string, err error) *UrlService_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UrlService_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (string, error)) *UrlService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type UrlService
func (_mock *UrlService) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UrlService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type UrlService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *UrlService_Expecter) Ping(ctx interface{}) *UrlService_Ping_Call {
	return &UrlService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *UrlService_Ping_Call) Run(run func(ctx context.Context)) *UrlService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(arg0)
	})
	return _c
}

func (_c *UrlService_Ping_Call) Return(err error) *UrlService_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UrlService_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *UrlService_Ping_Call {
	_c.Call.Return(run)
	return _c
}
