// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/MaximVebDevJs/go-u-shr/internal/service/url"
	mock "github.com/stretchr/testify/mock"
)

// NewUrlService creates a new instance of UrlService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUrlService(t interface {
	mock.TestingT
	Cleanup(func())
}) *UrlService {
	mock := &UrlService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// UrlService is an autogenerated mock type for the UrlService type
type UrlService struct {
	mock.Mock
}

type UrlService_Expecter struct {
	mock *mock.Mock
}

func (_m *UrlService) EXPECT() *UrlService_Expecter {
	return &UrlService_Expecter{mock: &_m.Mock}
}

// BatchCreate provides a mock function for the type UrlService
func (_mock *UrlService) BatchCreate(ctx context.Context, userID string, items []url.BatchItem) ([]url.BatchResult, error) {
	ret := _mock.Called(ctx, userID, items)

	if len(ret) == 0 {
		panic("no return value specified for BatchCreate")
	}

	var r0 []url.BatchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []url.BatchItem) ([]url.BatchResult, error)); ok {
		return returnFunc(ctx, userID, items)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []url.BatchItem) []url.BatchResult); ok {
		r0 = returnFunc(ctx, userID, items)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]url.BatchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, []url.BatchItem) error); ok {
		r1 = returnFunc(ctx, userID, items)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UrlService_BatchCreate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchCreate'
type UrlService_BatchCreate_Call struct {
	*mock.Call
}

// BatchCreate is a helper method to define mock.On call
//   - ctx
//   - userID
//   - items
func (_e *UrlService_Expecter) BatchCreate(ctx interface{}, userID interface{}, items interface{}) *UrlService_BatchCreate_Call {
	return &UrlService_BatchCreate_Call{Call: _e.mock.On("BatchCreate", ctx, userID, items)}
}

func (_c *UrlService_BatchCreate_Call) Run(run func(ctx context.Context, userID string, items []url.BatchItem)) *UrlService_BatchCreate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].([]url.BatchItem))
	})
	return _c
}

func (_c *UrlService_BatchCreate_Call) Return(batchResults []url.BatchResult, err error) *UrlService_BatchCreate_Call {
	_c.Call.Return(batchResults, err)
	return _c
}

func (_c *UrlService_BatchCreate_Call) RunAndReturn(run func(ctx context.Context, userID string, items []url.BatchItem) ([]url.BatchResult, error)) *UrlService_BatchCreate_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type UrlService
func (_mock *UrlService) Create(ctx context.Context, userID string, originalURL string) (string, error) {
	ret := _mock.Called(ctx, userID, originalURL)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (string, error)); ok {
		return returnFunc(ctx, userID, originalURL)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) string); ok {
		r0 = returnFunc(ctx, userID, originalURL)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, userID, originalURL)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UrlService_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type UrlService_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx
//   - userID
//   - originalURL
func (_e *UrlService_Expecter) Create(ctx interface{}, userID interface{}, originalURL interface{}) *UrlService_Create_Call {
	return &UrlService_Create_Call{Call: _e.mock.On("Create", ctx, userID, originalURL)}
}

func (_c *UrlService_Create_Call) Run(run func(ctx context.Context, userID string, originalURL string)) *UrlService_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *UrlService_Create_Call) Return(s string, err error) *UrlService_Create_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UrlService_Create_Call) RunAndReturn(run func(ctx context.Context, userID string, originalURL string) (string, error)) *UrlService_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type UrlService
func (_mock *UrlService) Get(ctx context.Context, id string) (string, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UrlService_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type UrlService_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx
//   - id
func (_e *UrlService_Expecter) Get(ctx interface{}, id interface{}) *UrlService_Get_Call {
	return &UrlService_Get_Call{Call: _e.mock.On("Get", ctx, id)}
}

func (_c *UrlService_Get_Call) Run(run func(ctx context.Context, id string)) *UrlService_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UrlService_Get_Call) Return(s string, err error) *UrlService_Get_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *UrlService_Get_Call) RunAndReturn(run func(ctx context.Context, id string) (string, error)) *UrlService_Get_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserURLs provides a mock function for the type UrlService
func (_mock *UrlService) GetUserURLs(ctx context.Context, userID string) ([]url.UserURL, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserURLs")
	}

	var r0 []url.UserURL
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]url.UserURL, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []url.UserURL); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]url.UserURL)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// UrlService_GetUserURLs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserURLs'
type UrlService_GetUserURLs_Call struct {
	*mock.Call
}

// GetUserURLs is a helper method to define mock.On call
//   - ctx
//   - userID
func (_e *UrlService_Expecter) GetUserURLs(ctx interface{}, userID interface{}) *UrlService_GetUserURLs_Call {
	return &UrlService_GetUserURLs_Call{Call: _e.mock.On("GetUserURLs", ctx, userID)}
}

func (_c *UrlService_GetUserURLs_Call) Run(run func(ctx context.Context, userID string)) *UrlService_GetUserURLs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string))
	})
	return _c
}

func (_c *UrlService_GetUserURLs_Call) Return(userURLs []url.UserURL, err error) *UrlService_GetUserURLs_Call {
	_c.Call.Return(userURLs, err)
	return _c
}

func (_c *UrlService_GetUserURLs_Call) RunAndReturn(run func(ctx context.Context, userID string) ([]url.UserURL, error)) *UrlService_GetUserURLs_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type UrlService
func (_mock *UrlService) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// UrlService_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type UrlService_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx
func (_e *UrlService_Expecter) Ping(ctx interface{}) *UrlService_Ping_Call {
	return &UrlService_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *UrlService_Ping_Call) Run(run func(ctx context.Context)) *UrlService_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *UrlService_Ping_Call) Return(err error) *UrlService_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *UrlService_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *UrlService_Ping_Call {
	_c.Call.Return(run)
	return _c
}
